/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './Components/**/*.razor',
    './wwwroot/**/*.html'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        // Material Theme tokens. Values live in Styles/app.css as RGB triplets so
        // the same utility works in both light and dark mode.
        "on-secondary": "rgb(var(--cl-on-secondary) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--cl-on-secondary-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--cl-surface-container-high) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--cl-tertiary-fixed) / <alpha-value>)",
        "surface-container-low": "rgb(var(--cl-surface-container-low) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--cl-surface-container-lowest) / <alpha-value>)",
        "secondary": "rgb(var(--cl-secondary) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--cl-inverse-on-surface) / <alpha-value>)",
        "secondary-container": "rgb(var(--cl-secondary-container) / <alpha-value>)",
        "surface-tint": "rgb(var(--cl-surface-tint) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--cl-secondary-fixed) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--cl-on-surface-variant) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--cl-on-primary-fixed) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--cl-surface-container-highest) / <alpha-value>)",
        "tertiary-container": "rgb(var(--cl-tertiary-container) / <alpha-value>)",
        "surface-container": "rgb(var(--cl-surface-container) / <alpha-value>)",
        "on-error": "rgb(var(--cl-on-error) / <alpha-value>)",
        "surface-dim": "rgb(var(--cl-surface-dim) / <alpha-value>)",
        "primary-container": "rgb(var(--cl-primary-container) / <alpha-value>)",
        "on-error-container": "rgb(var(--cl-on-error-container) / <alpha-value>)",
        "on-tertiary": "rgb(var(--cl-on-tertiary) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--cl-tertiary-fixed-dim) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--cl-on-primary-fixed-variant) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--cl-on-tertiary-container) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--cl-secondary-fixed-dim) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--cl-on-tertiary-fixed) / <alpha-value>)",
        "on-primary-container": "rgb(var(--cl-on-primary-container) / <alpha-value>)",
        "background": "rgb(var(--cl-background) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--cl-primary-fixed-dim) / <alpha-value>)",
        "outline-variant": "rgb(var(--cl-outline-variant) / <alpha-value>)",
        "on-surface": "rgb(var(--cl-on-surface) / <alpha-value>)",
        "surface-bright": "rgb(var(--cl-surface-bright) / <alpha-value>)",
        "primary-fixed": "rgb(var(--cl-primary-fixed) / <alpha-value>)",
        "inverse-primary": "rgb(var(--cl-inverse-primary) / <alpha-value>)",
        "tertiary": "rgb(var(--cl-tertiary) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--cl-on-secondary-fixed-variant) / <alpha-value>)",
        "error-container": "rgb(var(--cl-error-container) / <alpha-value>)",
        "primary": "rgb(var(--cl-primary) / <alpha-value>)",
        "surface": "rgb(var(--cl-surface) / <alpha-value>)",
        "error": "rgb(var(--cl-error) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--cl-on-secondary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--cl-on-tertiary-fixed-variant) / <alpha-value>)",
        "inverse-surface": "rgb(var(--cl-inverse-surface) / <alpha-value>)",
        "on-primary": "rgb(var(--cl-on-primary) / <alpha-value>)",
        "surface-variant": "rgb(var(--cl-surface-variant) / <alpha-value>)",
        "outline": "rgb(var(--cl-outline) / <alpha-value>)",
        "on-background": "rgb(var(--cl-on-background) / <alpha-value>)",

        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          900: '#0f172a'
        },
        executive: {
          gold: '#D4AF37',
          'gold-light': '#F2CA50',
          'gold-dark': '#B38F24',
          indigo: '#6366F1',
          'indigo-light': '#818CF8',
          'indigo-dark': '#4F46E5',
          steel: '#94A3B8',
          canvas: '#0A0D14',
          'canvas-dim': '#10131A',
          card: '#111622',
          'card-hover': '#161C2C',
          elevated: '#182030',
          modal: '#151B2B',
          'border-subtle': 'rgba(255, 255, 255, 0.08)',
          'border-hover': 'rgba(255, 255, 255, 0.16)',
          'border-gold': 'rgba(212, 175, 55, 0.25)',
          'border-indigo': 'rgba(99, 102, 241, 0.35)',
          'text-primary': '#E1E2EC',
          'text-secondary': '#94A3B8',
          'text-muted': '#64748B'
        },
        nocturne: {
          canvas: '#0A0D14',
          card: '#111622',
          elevated: '#182030',
          border: 'rgba(255, 255, 255, 0.08)',
          'border-focus': 'rgba(212, 175, 55, 0.35)',
          'text-primary': '#E1E2EC',
          'text-secondary': '#94A3B8',
          'text-muted': '#64748B'
        }
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "1.5rem",
        "margin-desktop": "3rem",
        "gutter": "1.5rem",
        "gutter-desktop": "2rem"
      },
      fontSize: {
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "label-lg": ["13px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-md": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}